# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3ad3b67846afbc3a67a050d58ad9db5b7ab209902738916d63125ee4909623dea1f32970057231dad042fee066ea6abb44b6960d6620e54653669b01dbcde6

test:
  secret_key_base: a8d89bd7e4d7b4a616fe3bad4162b4c645de3eecc096426ef5103e12437bd47558bf147811d998742b09cbfff2aba3190d5cf59d93c42cf601de0108646d2631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
